// Code generated by zap MarshalLogObject generator; DO NOT EDIT.

package examples

import "go.uber.org/zap/zapcore"

// MarshalLogObject zapcore.ObjectMarshaler interface method
func (l *ExampleLog) MarshalLogObject(enc zapcore.ObjectEncoder) error {
		var err error
		err = enc.AddReflected("base_log", *l.BaseLog)
		if err != nil { return err }
		err = enc.AddReflected("base_array_log", l.BaseArrayLog)
		if err != nil { return err }
		enc.AddBool("bool", l.Bool)
		enc.AddBool("bool_ptr", *l.BoolPtr)
		enc.AddComplex128("complex_128", l.Complex128)
		enc.AddComplex128("complex_128_ptr", *l.Complex128Ptr)
		enc.AddComplex64("complex_64", l.Complex64)
		enc.AddComplex64("complex_64_ptr", *l.Complex64Ptr)
		enc.AddFloat64("float_64", l.Float64)
		enc.AddFloat64("float_64_ptr", *l.Float64Ptr)
		enc.AddFloat32("float_32", l.Float32)
		enc.AddFloat32("float_32_ptr", *l.Float32Ptr)
		enc.AddInt("int", l.Int)
		enc.AddInt("int_ptr", *l.IntPtr)
		enc.AddInt64("int_64", l.Int64)
		enc.AddInt64("int_64_ptr", *l.Int64Ptr)
		enc.AddInt32("int_32", l.Int32)
		enc.AddInt32("int_32_ptr", *l.Int32Ptr)
		enc.AddInt16("int_16", l.Int16)
		enc.AddInt16("int_16_ptr", *l.Int16Ptr)
		enc.AddInt8("int_8", l.Int8)
		enc.AddInt8("int_8_ptr", *l.Int8Ptr)
		enc.AddString("string", l.String)
		enc.AddString("string_ptr", *l.StringPtr)
		enc.AddUint("uint", l.Uint)
		enc.AddUint("uint_ptr", *l.UintPtr)
		enc.AddUint64("uint_64", l.Uint64)
		enc.AddUint64("uint_64_ptr", *l.Uint64Ptr)
		enc.AddUint32("uint_32", l.Uint32)
		enc.AddUint32("uint_32_ptr", *l.Uint32Ptr)
		enc.AddUint16("uint_16", l.Uint16)
		enc.AddUint16("uint_16_ptr", *l.Uint16Ptr)
		enc.AddUint8("uint_8", l.Uint8)
		enc.AddUint8("uint_8_ptr", *l.Uint8Ptr)
		enc.AddBinary("bytes", l.Bytes)
		enc.AddUintptr("uint_ptr_val", l.UintPtrVal)
		enc.AddUintptr("uint_ptr_val_ptr", *l.UintPtrValPtr)
		enc.AddTime("time", l.Time)
		enc.AddTime("time_ptr", *l.TimePtr)
		enc.AddDuration("duration", l.Duration)
		enc.AddDuration("duration_ptr", *l.DurationPtr)
		err = enc.AddReflected("map", l.Map)
		if err != nil { return err }
		enc.AddString("my_id", l.CustomID)
		return err	
}
